### ISSUE TITLE
按教程写到 协程创建8 时, 执行 php test.php 程序挂起了没有退出

### ISSUE THREAD

**Issue by luffluo** [php-extension-research/study#11]
执行 `php test.php` 后输出如下
```shell
bash-4.4# php test.php
main coroutine
coroutine[1] create successfully
a
b
main coroutine

```

问下, 有什么方法调试看, 为什么挂起了吗?

**Comment by huanghantao** [comment]
gdb单步调试



---原始邮件---
发件人: "Luff Luo"<notifications@github.com&gt;
发送时间: 2020年12月23日(周三) 晚上9:37
收件人: "php-extension-research/study"<study@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [php-extension-research/study] 按教程写到 协程创建8 时, 执行 php test.php 程序挂起了没有退出 (#11)




 
执行 php test.php 后输出如下
 bash-4.4# php test.php main coroutine coroutine[1] create successfully a b main coroutine 
 
问下, 有什么方法调试看, 为什么挂起了吗?
