### ISSUE TITLE
关于结构体zend_fcall_info的一点疑问

### ISSUE THREAD

**Issue by linixyz** [php-extension-research/study#3]
疑问：结构体成员params是一个zval的指针，但是怎么看出来它是一个数组呢？
我在【[协程创建（四）](https://github.com/php-extension-research/study/blob/master/docs/《PHP扩展开发》-协程-协程创建（四）.md)】看到，当给task方法传递$a,$b两个参数时，在gdb里调试，p *fci.params[0].value.str.val@1，p *fci.params[1].value.str.val@1。

**Comment by huanghantao** [comment]
@yangclsir 在解析参数的时候，可以通过第二个参数fci.param_count知道传递了几个参数。
