### ISSUE TITLE
关于协程开发选用开发语言的疑问

### ISSUE THREAD

**Issue by linixyz** [php-extension-research/study#4]
发现在swoole源码中出现了c++，本教程开发的协程也使用了c++，请问是因为c++在开发协程方面有固有的优势，还是开发者个人意愿？

**Comment by huanghantao** [comment]
@yangclsir 
c++有很多容器，可以快速开发。
例如定时器，swoole自己实现了一个堆，算是历史遗留的问题。但是，在本教程，没有自己去实现堆，而是用到了C++ stl的优先队列。
